export enum PermissionEnum {
    CREATE_MINTER = 'CREATE_MINTER',
    VIEW_MINTER = 'VIEW_MINTER',
    UPDATE_MINTER = 'UPDATE_MINTER',
    DELETE_MINTER = 'DELETE_MINTER',
    CREATE_TEABAG = 'CREATE_TEABAG',
    VIEW_TEABAG = 'VIEW_TEABAG',
    UPDATE_TEABAG = 'UPDATE_TEABAG',
    DELETE_TEABAG = 'DELETE_TEABAG',
    CREATE_NFTS = 'CREATE_NFTS',
    VIEW_NFTS = 'VIEW_NFTS',
    DELETE_NFTS = 'DELETE_NFTS',
    CREATE_NOTIFICATIONS = 'CREATE_NOTIFICATIONS',
    VIEW_NOTIFICATIONS = 'VIEW_NOTIFICATIONS'
}